name: npm-publish
on:                                 #在main分支上进行push时触发  
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
        
    steps:                          
    - name: checkout master
      uses: actions/checkout@v2
      with:
        ref: master
            
    - name: install nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '13.x'
      
    - name: configue taro and build
      run: |
        yarn global add @tarojs/cli@1.3.46   
        yarn install
        yarn build:weapp
        
    - name: npm publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
